export const FEATURE_PRODUCT_REQUEST = "FEATURE_PRODUCT_REQUEST";
export const FEATURE_PRODUCT_SUCCESS = "FEATURE_PRODUCT_SUCCESS";
export const FEATURE_PRODUCT_FAIL = "FEATURE_PRODUCT_FAIL";

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

// ! ======================================
// !      admin constants
// ! ======================================

//TODO --->all prdoucts list
export const ADMIN_PRODUCTLIST_REQUEST = "ADMIN_PRODUCTLIST_REQUEST";
export const ADMIN_PRODUCTLIST_SUCCESS = "ADMIN_PRODUCTLIST_SUCCESS";
export const ADMIN_PRODUCTLIST_FAIL = "ADMIN_PRODUCTLIST_FAIL";

// TODO -----> creating a new product
export const ADMIN_NEW_PRODUCT_REQUEST = "ADMIN_NEW_PRODUCT_REQUREST";
export const ADMIN_NEW_PRODUCT_SUCCESS = "ADMIN_NEW_PRODUCT_RSUCCESS";
export const ADMIN_NEW_PRODUCT_FAIL = "ADMIN_NEW_PRODUCT_FAIL";
export const ADMIN_NEW_PRODUCT_RESET = "ADMIN_NEW_PRODUCT_RESET";

// TODO ---> Deleting the product
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

// TODO ---> update the product
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

// TODO ----> getting all categories
export const ADMIN_GET_CATEGORY_REQUEST = "ADMIN_GET_CATEGORY_REQUEST";
export const ADMIN_GET_CATEGORY_SUCCESS = "ADMIN_GET_CATEGORY_SUCCESS";
export const ADMIN_GET_CATEGORY_FAIL = "ADMIN_GET_CATEGORY_FAIL";

// TODO ---> add new Category
export const ADMIN_CREATE_CATEGORY_REQUEST = "ADMIN_CREATE_CATEGORY_REQUEST";
export const ADMIN_CREATE_CATEGORY_SUCCESS = "ADMIN_CREATE_CATEGORY_SUCCESS";
export const ADMIN_CREATE_CATEGORY_FAIL = "ADMIN_CREATE_CATEGORY_FAIL";
export const ADMIN_CREATE_CATEGORY_RESET = "ADMIN_CREATE_CATEGORY_RESET";

// TODO ---> Delete Category
export const ADMIN_DELETE_CATEGORY_REQUEST = "ADMIN_DELETE_CATEGORY_REQUEST";
export const ADMIN_DELETE_CATEGORY_SUCCESS = "ADMIN_DELETE_CATEGORY_SUCCESS";
export const ADMIN_DELETE_CATEGORY_FAIL = "ADMIN_DELETE_CATEGORY_FAIL";
export const ADMIN_DELETE_CATEGORY_RESET = "ADMIN_DELETE_CATEGORY_RESET";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
